### PR TITLE
added verification warning

### PR DESCRIPTION
**Pull request by alangecker**
- [X] basic implementation
- [ ] i18n
- [ ] tests

### CODE REVIEW

**Comment by tiltec** [comment]
Maybe you can use MainAlerts (using vuex `alerts/create` to show the warning on the main page?

**Comment by alangecker** [comment]
@tiltec but, as far as I understand, there is no option for having buttons and state in the MainAlerts like it is used in the VerificationWarning right now?

**Comment by tiltec** [comment]
Maybe MainAlert with a link to settings to resend the verify email? so it's in addition to the work you did here

**Comment by alangecker** [comment]
@tiltec but when you are on the settings it shouldn't be shown twice, so the MainAlert would need to be hidden in that case.
I would just merge it like that and maybe adding global warning later

**Comment by tiltec** [comment]
Ok, then merge ahead :) It was just me thinking out loud.
Do you need approval before merging?

**Comment by alangecker** [comment]
with the current procedure i guess it doesn't really matter :D

**Pull request merged**
