### PR TITLE
add mobile number field to relevant pages

### PR DESCRIPTION
**Pull request by DevipriyaSarkar**
Add mobile number field to profile page (references issue https://github.com/yunity/karrot-frontend/issues/552)

### CODE REVIEW

**Comment by tiltec** [comment]
Congratulations for getting started with Vue and Quasar! Looks good so far.

Now the user needs to be able to edit the phone number field too. A new input field in the `ProfileEdit` component could be the solution.

**Comment by DevipriyaSarkar** [comment]
This would be on the settings page right?

**Comment by tiltec** [comment]
Yes :+1:

**Comment by tiltec** [comment]
Seems good to me! Are you happy with how it is? If you're ready to merge, can you update the snapshots by running `yarn test -u` and commit it?

@D0nPiano what do you think about it?

**Comment by D0nPiano** [comment]
Maybe you could add a little more margin between email and phone (just replace `info-item` class with `info` class?) and between the items on settings (just a thing I noticed, not really related to the PR):
```
.q-field
  margin 3em 0
```

...but other than that - looks good! :+1:

**Comment by DevipriyaSarkar** [comment]
Sure. I will update these things :)

**Pull request merged**
