### PR TITLE
Feedback UI

### PR DESCRIPTION
**Pull request by D0nPiano**
### First drafts of feedback & statistics components

**Adds**
- FeedbackItem
- FeedbackList

**Improves**
- Amount Box

**Teaser**  
screenshot from 2017-12-20 11-41-34

**ToDos**
- [x] Feedback Item: Correctly add date for pickup
- [x] Add Feedback List Pages for store and group
- [x] Create picker for feedback creation form -> "Which pickup do you want to feedback?"
- [x] (optional) create Notification "you can give feedback" somewhere

### CODE REVIEW

**Comment by tiltec** [comment]
I merged recent changes from master and fixed codestyle changes.

**Comment by D0nPiano** [comment]
@tiltec I think the components are pretty much ready from a UI perspective. Would you be willing to work on the store side a bit? Also, if you need anything else UI wise, let me know.

The components are mostly added with hardcoded values (e.g. the notice on the group page, the feedback pages, the feedback options in `@/statistics/PickupFeedback`) at the moment. Didn't know how to test it otherwise not using the store.

**Comment by tiltec** [comment]
I started working on it, but I will do some backend changes as well to simplify the frontend implementation so it might take a few days!

**Comment by tiltec** [comment]
Ok! I had a nice time of combined front/backend coding and this came out of it. I think it should work, but you need [this backend patch](https://github.com/yunity/karrot-backend/pull/466) to try it out.

My proposal would be to merge this PR and the backend patch soonish and then continue working on improving the feedback UI. I'll add some of my points to #639 to track and perhaps discuss them.
What do you think?

**Pull request merged**
