### PR TITLE
loader animation updated

### PR DESCRIPTION
**Pull request by chocos10**
Fixes this #988

### CODE REVIEW

**Comment by mr-kojo** [comment]
When you're done, please run `yarn test -u` and commit the updated UI snapshots so that the tests pass.

**Comment by tiltec** [comment]
Do we still need to set `:value`  on each button?

Quasar documentation is a bit confusing to me. http://quasar-framework.org/components/button.html#Button-with-Progress mentions the method with `:loading`, http://quasar-framework.org/components/button.html#Controlling-the-Button-for-Form-Submission mentions another method with `v-model`.

**Comment by chocos10** [comment]
@tiltec  even i was confused so i didn't removed that .

**Comment by chocos10** [comment]
@tiltec  What should i do remove :value or let it be for now ?

**Comment by tiltec** [comment]
@chocos10 What happens if you remove it?

**Comment by chocos10** [comment]
@tiltec for now it does not disturb anything on the following page but i don't know if the :value is used somewhere else in the codebase.

**Comment by chocos10** [comment]
@tiltec  for now i have removed :value as i didn't find any problem after removing that.

**Comment by tiltec** [comment]
Cool! Can you update the snapshots again? Then it should be ready to merge!

**Comment by chocos10** [comment]
@tiltec done :+1:

**Pull request merged**
