### PR TITLE
add changeEmail component

### LINKED ISSUE #698: Missing change-email frontend
The settings page currently only says "Mail" at the bottom, should add the functionality to let users change their e-mail address.

### PR DESCRIPTION
**Pull request by tiltec**
I moved the verificationWarning closer to changeEmail in settings

image

Closes #698

### CODE REVIEW

**Comment by nicksellen** [comment]
I know this is just about the frontend component but I got a bit confused with the change email functionality:
- changing it to the email address of another user gives a 400 error, but no error is shown on the page, additionally the field keeps the changed email address so it looks like it worked
- I changed it to something else, and it seems like it was immediately updated as it only showed the changed one (although I still have to login with the old email address which is not shown)
- I couldn't click on the verification email link as they are dummy email accounts, but also could not change the email address back to what it was before 

Although as it has `email` and `unverifiedEmail` address fields it seems like it should support this.

I think this is one of the UI/UX things we would benefit from just copying from <some popular site> (airbnb, etc...).

For now though, maybe just showing that there is a pending email address change separately from the current email address?

**Comment by tiltec** [comment]
You're right, the change-email implementation in some ways.

> changing it to the email address of another user gives a 400 error, but no error is shown on the page, additionally the field keeps the changed email address so it looks like it worked

True, I was kind of waiting for #668 before adding it. We could leave this PR around until #668 is done and the add the necessary bits, or implement it in the "old" boilerplate-y way (I'm not so motivated right now), or just leave it out for now.

> I changed it to something else, and it seems like it was immediately updated as it only showed the changed one (although I still have to login with the old email address which is not shown)

Ah right, this is one of this bits I forgot to copy from the old angular page. I think we should show the old verified email in the email field. If there is no verified email, show the unverified one.

> could not change the email address back to what it was before

I discovered this too yesterday, it seems like a backend issue. Will open an issue there.

> I think this is one of the UI/UX things we would benefit from just copying from (airbnb, etc...).

That would be great. I think this was one of the features where I went into the trap thinking of an "uninteresting but necessary and easy-to-implement" thing and getting surprised by the huge number of states that need to be handled. Maybe also "django-allauth" or similar could help us there.

**Comment by tiltec** [comment]
Backend issue: https://github.com/yunity/karrot-backend/issues/430

**Comment by tiltec** [comment]
I added the change-email thing to the list in #668

**Pull request merged**
