### PR TITLE
fix select group at profile page

### PR DESCRIPTION
**Pull request by brnsolikyl**
## What does this PR do?

There was a problem with the casing that made the button to switch groups at someone's profile page not to work.

## Checklist

- [ ] added a test, or explain why one is not needed/possible...
- [ ] no unrelated changes
- [ ] asked someone for a code review
- [ ] joined [chat.foodsaving.world/channel/karrot-dev](https://chat.foodsaving.world/channel/karrot-dev)
- [ ] added an entry to CHANGELOG.md (description, pull request link, username(s))

### CODE REVIEW

**Comment by tiltec** [comment]
It seems you somehow changed the yarn.lock file, could you reset it?

**Comment by brnsolikyl** [comment]
Oops! I was wondering about that... It might have happened when I had to update yarn, because it wasn't working here anymore. I'll take a look into it. Any tips to spare me some time? :)

**Comment by brnsolikyl** [comment]
So I just copy-pasted the file from the master branch. But still wondering how/why that change happened.

**Review by nicksellen — APPROVED** [review]
Looks good!

**Comment by nicksellen** [comment]
(btw you are free to merge when ready!)

**Comment by brnsolikyl** [comment]
Cool, pressing the Merge button for the first time! :)

**Pull request merged**
