### PR TITLE
Upgrade font awesome to v5 

### PR DESCRIPTION
**Pull request by ananya-agrawal**
issue no: #820

### CODE REVIEW

**Comment by nicksellen** [comment]
Looks good!

You can fix the failing snapshot tests by running `yarn test -u` and then add/commit/push the resulting snapshot files.

Also looks like you might need to rebase on top of the latest master, and resolve the conflict it mentions.

A few little details that seem to be broken (looking at the [netlify deploy preview](https://deploy-preview-961--karrot.netlify.com/#/group/4/wall) and comparing to https://dev.karrot.world/):

Some of the circular buttons have slightly misaligned icons now (they also all seem a little bigger?):

broken1

broken3

The map pins are missing their icons, and when the store markers are enabled the green check mark is missing.

broken2

**Comment by tiltec** [comment]
The misaligned icons seem weird, so far Quasar took care of aligning them properly. Maybe there's an update in Quasar 0.15 that handles this? #913

**Comment by ananya-agrawal** [comment]
whether the alignment should be done by adjusting the height and the width of element ?

**Comment by nicksellen** [comment]
It would be to nice to have them aligned, but the implementation could be temporary solution until the quasar 0.15 upgrade is done.

I didn't look at the existing CSS, but `position: relative` allows you to define an offset relative to it's position (in combination with top/right/bottom/left attributes), so might be a solution with that.

**Comment by tiltec** [comment]
I came quite far with upgrading to Quasar 0.15 in the last days, so you could merge https://github.com/yunity/karrot-frontend/pull/974 into your branch and see if the icons are aligned nicely by default. Then we don't need lots of custom inline styles.

Note this section in the Quasar upgrade guide regarding font awesome icons: http://quasar-framework.org/guide/quasar-upgrade-guide.html#Icon-Packs

**Comment by ananya-agrawal** [comment]
please review it once

**Comment by ananya-agrawal** [comment]
@tiltec please review

**Comment by ananya-agrawal** [comment]
@tiltec do review, done required changes.

**Pull request merged**
