### PR TITLE
tried to upgrade fontawesome

### PR DESCRIPTION
**Pull request by anishaagrawal**

### CODE REVIEW

**Comment by tiltec** [comment]
Hi @anishaagrawal this Pull Request is quite big, it seems like you added all files of Font Awesome to our repository instead of adding them as dependency. This makes the PR very hard to review and leads to much code duplication.

If you upgrade the package `quasar-extras` to the latest version, the site will use font-awesome by default. (described here: https://github.com/yunity/karrot-frontend/issues/820#issuecomment-362906853 )

**Comment by tiltec** [comment]
It looks like version you pushed is still using Font Awesome 4: https://deploy-preview-899--karrot.netlify.com/
Or maybe there's no difference?

**Comment by anishaagrawal** [comment]
Ok.. I will try to use it as dependencies by upgrading quasar.
Do i need to change anything more to upgrade to FA5.
Thanks

**Comment by anishaagrawal** [comment]
i have reinstalled the quasar-extras to upgrade it. but may be its not
working.Is it proper way to upgrade. please guide.


On 26 February 2018 at 20:54, Anisha Agrawal <anisha.agrawalindian@gmail.com
> wrote:

> Ok.. I will try to use it as dependencies by upgrading quasar.
> Do i need to change anything more to upgrade to FA5.
> Thanks
>

**Comment by tiltec** [comment]
Maybe it makes sense to start from a fresh `master`, run the appropriate yarn command to upgrade `quasar-extras` to the latest version and then view the changes in your browser. You might see a few missing icons then. At this point, can you make a screenshot and post it in here?
Then we can work together to fix the missing icons.

**Comment by tiltec** [comment]
@anishaagrawal are you motivated to give it another try?

**Pull request closed without merging**
