### PR TITLE
WIP: Group Banners

### PR DESCRIPTION
**Pull request by D0nPiano**
Like store banners, groups could have some sort of banner to make them look different from other stores.

To differentiate between stores and groups, I made groups have random circles instead of the rectangles.

### Example
groupbanner

### CODE REVIEW

**Comment by D0nPiano** [comment]
Okay, apperently I was way to motivated. Still need to look through the code and make it better, but the visible changes should all be done. Please let me know what you think from a UI perspective.

### Mayor changes
- Added GroupBanner (RandomArt changes)
- new Layout of Invitations
- new Layout of Description

### Possible next ToDos
- [ ] rethink GroupDescription, maybe split it into two pages again
- [ ] add GroupBanner to edit group (and maybe feedback and pickups)
- [ ] remove some of the buttons in the (...)-group-menu
- [ ] code cleanup
- [ ] fix some margins

## Screenshots
### New (public, desktop) Description page


### New (private, mobile) Description page


### New Invite page


### New Store NavBar

**Comment by D0nPiano** [comment]
Okay, since it's become quite a large PR we should probably merge it first and continue working on it the. Just went through a first code review, but would be happy for input.

Also, I just changed RandomArt-circles again to be a little darker. Might remove the darkening background-color css stuff completely then. Looks like this now:

invitations

**Comment by tiltec** [comment]
Looks good so far! Thanks for the initiative and taking care of mobile. Maybe we can allow groups to choose their color/style themselves in future :) I also like the additional floating action buttons.

A few design nitpicks, maybe you can work around or fix them:

- "all groups" view is not spanning the whole screen anymore (left-aligned instead), looks a bit off to me.

image

- A bit too much margin below topbar

image

- Red error text has low contrast with dark background

image

**Comment by D0nPiano** [comment]
You actually found an already existing error! -> Fixed it.
I could reproduce the topbar margin error though (Chrome & Firefox both worked fine) - what browser are you using?
And I removed the red font-color of group invitations on error. You probably read the message anyways when you can't click the button.

**Comment by tiltec** [comment]
Great!

I would still argue that the contrast on the invite page is too low:

image

Maybe making the text white instead of grey would be enough? Is the random art for groups generally dark blue?

**Comment by D0nPiano** [comment]
Yeah, agreed. Changed it to white now.

The randomArt is generally green/blue/beige-ish for groups. See the gif a few comments up. I am still unsure about the general contrast - it's just one number in app.variables to change though. So if we get feedback to make it a bit darker, it shouldn't be too much work ;)

**Comment by tiltec** [comment]
This PR cause a big red warning while running tests, any idea where it comes from?

```
      TypeError: Cannot read property 'getters' of undefined
          at VueComponent.mappedGetter (/home/tic/Development/foodsaving-frontend/node_modules/vuex/dist/vuex.common.js:850:73)
          at Watcher.get (/home/tic/Development/foodsaving-frontend/node_modules/vue/dist/vue.runtime.common.js:3113:25)
          at Watcher.evaluate (/home/tic/Development/foodsaving-frontend/node_modules/vue/dist/vue.runtime.common.js:3220:21)
          at Proxy.computedGetter (/home/tic/Development/foodsaving-frontend/node_modules/vue/dist/vue.runtime.common.js:3472:17)
          at /home/tic/Development/foodsaving-frontend/node_modules/vuex-connect/dist/vuex-connect.common.js:36:12
          at Array.forEach (<anonymous>)
          at pick (/home/tic/Development/foodsaving-frontend/node_modules/vuex-connect/dist/vuex-connect.common.js:35:8)
          at Proxy.options.render (/home/tic/Development/foodsaving-frontend/node_modules/vuex-connect/dist/vuex-connect.common.js:166:14)
          at VueComponent.Vue._render (/home/tic/Development/foodsaving-frontend/node_modules/vue/dist/vue.runtime.common.js:4472:22)
          at renderComponentInner (/home/tic/Development/foodsaving-frontend/node_modules/vue-server-renderer/build.js:7356:25)
          at renderComponent (/home/tic/Development/foodsaving-frontend/node_modules/vue-server-renderer/build.js:7326:5)
          at renderNode (/home/tic/Development/foodsaving-frontend/node_modules/vue-server-renderer/build.js:7242:5)
          at render (/home/tic/Development/foodsaving-frontend/node_modules/vue-server-renderer/build.js:7571:5)
          at Object.renderToString (/home/tic/Development/foodsaving-frontend/node_modules/vue-server-renderer/build.js:8049:9)
          at _callee$ (/home/tic/Development/foodsaving-frontend/src/storyshots.spec.js:58:35)
          at tryCatch (/home/tic/Development/foodsaving-frontend/node_modules/regenerator-runtime/runtime.js:62:40)
          at Generator.invoke [as _invoke] (/home/tic/Development/foodsaving-frontend/node_modules/regenerator-runtime/runtime.js:296:22)
          at Generator.prototype.(anonymous function) [as next] (/home/tic/Development/foodsaving-frontend/node_modules/regenerator-runtime/runtime.js:114:21)
          at step (/home/tic/Development/foodsaving-frontend/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
          at /home/tic/Development/foodsaving-frontend/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
          at new Promise (<anonymous>)
          at new F (/home/tic/Development/foodsaving-frontend/node_modules/core-js/library/modules/_export.js:35:28)
          at Object.<anonymous> (/home/tic/Development/foodsaving-frontend/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
          at Object.asyncFn (/home/tic/Development/foodsaving-frontend/node_modules/jest-jasmine2/build/jasmine_async.js:129:432)
          at resolve (/home/tic/Development/foodsaving-frontend/node_modules/jest-jasmine2/build/queue_runner.js:51:12)
          at new Promise (<anonymous>)
          at mapper (/home/tic/Development/foodsaving-frontend/node_modules/jest-jasmine2/build/queue_runner.js:40:274)
          at promise.then (/home/tic/Development/foodsaving-frontend/node_modules/jest-jasmine2/build/queue_runner.js:83:39)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by tiltec** [comment]
It seems to be caused by HistoryList.story.js

**Comment by tiltec** [comment]
Ah, the code move from `HistoryList` to `HistoryListUI` broke storybook, will fix. Please take care in future. I also forgot checking the snapshot, it's quite obvious that the whole HistoryList snapshot got removed.

**Pull request merged**
