### PR TITLE
Disable save photo button if photo wasn't changed

### LINKED ISSUE #860: [Settings page] Disable "save photo" button if photo wasn't changed
image

This button should only be enabled if the photo was changed, to aid the user.

### PR DESCRIPTION
**Pull request by LyraXaph**
Ready for review :)  Fixes #860

### CODE REVIEW

**Comment by tiltec** [comment]
Looks good! To fix the failing test, please update the snapshot: run `yarn test -u` and commit the changed file.

**Comment by LyraXaph** [comment]
I did as instructed, but I don't think the issue is solved?

**Comment by tiltec** [comment]
Ah I see. That's not your fault, but some problem with nodeJS not using UTC as time zone during snapshot creation. I fixed it a while ago, but the fix didn't seem to work on your machine.

I will update the snapshots and merge the PR. And maybe have another try at making nodeJS use UTC.

**Comment by tiltec** [comment]
Merged in https://github.com/yunity/karrot-frontend/commit/a40b921b001b2bc0e6ee4766af9074aacb3e5798

**Pull request closed without merging**
