### PR TITLE
WIP: New sidenav

### PR DESCRIPTION
**Pull request by nicksellen**
In the spirit of https://github.com/yunity/karrot-frontend/issues/683

Should also consider:
- [Improve navigation for typical user flows #958 ](https://github.com/yunity/karrot-frontend/issues/958)
- [Improve group sidenav #973](https://github.com/yunity/karrot-frontend/issues/973)

A few thoughts/questions that came up:
- should stores really have their own sections for pickups/feedback/etc or should it be filters on the group versions of those pages
- seems quite nice to have indented nested submenus for lesser used things that relate to the main item
- feedback could be nested under pickups
- maybe also nested under pickups, could be "My upcoming pickups" / "Pickups in need of someone..." / "manage pickups"
- description might not really deserve it's own menu
- the "edit group" button is on the description page, but that's for editing everything about the group
- maybe could have group name somewhere on left nav
- would be nice to open user profile in the context of the current group (not sure what to do if they are not in the current group)
- I missed off lots of things that were in the toolbars, they would need to go somewhere too

newsidebar

### CODE REVIEW

**Comment by tiltec** [comment]
Maybe most of the toolbar contents could get moved to an "action bar" on top of the page, similar to the actions buttons in store pickup view.

image

For the group wall, we could move the 3 alert bars into the toolbar, with a combination of icon+number per alert.

The map toggles (user on/off, stores on/off, fullscreen) could become something similar to leaflet map controls, floating inside the map.

**Comment by tiltec** [comment]
Group description, members and history could be joined into one "Details" sidenav entry?

**Comment by DougInAMug** [comment]
@nicksellen Do I interpret your screenshot correctly, that you are planning to have Store Pickups, Feedback and History nested below the Store? This would 'fix' the UI confusion Jess and I had when using Karrot yesterday. She mentioned that even switching the existing panes (i.e. having the Stores pane above the Store Pickup/Fedback/History) would also be better.

(Further to the Foodsharing Edinburgh meeting I attended 2018-07-02)

**Comment by nicksellen** [comment]
@DougInAMug yes that's how I did it there, but so far this is just an idea, I wanted to spend a bit more time thinking more deeply about user navigation as it is certainly a bit confusing at the moment. Actually when I showed people here that new UI they didn't see the Pickups/Feedback/History as nested. Another approach there is to use filters on the Group versions of those pages.

I think we need to introduce some new concepts or hierarchies to make the common things very clear and easy, and put the less frequently used things deeper in the navigation. Also, a bit more nesting (e.g. pickup feedback could be nested under pickups).

Input very welcome though! (especially with nice drawings!).

**Comment by nicksellen** [comment]
Closing in favour of https://github.com/yunity/karrot-frontend/pull/1071

**Pull request closed without merging**
