### PR TITLE
Resend invitation email

### LINKED ISSUE #837: Resend invitation email (assigned)
I want to add Maxi to foodsharing Wurzen. I sent her an invitation months ago, but she said she never received it.

I'd like to have a possibility to resend the invitation email. E.g with a pop-up that warns me that an invitation was already sent to this address, but still offers me to do it again.

### PR DESCRIPTION
**Pull request by mvellasco**
Closes #837 

Finished the tasks for the frontend.

### CODE REVIEW

**Comment by mvellasco** [comment]
Hello @tiltec, I made the changes to the code as requested. Hope it's everything alright now.

**Comment by tiltec** [comment]
Part of me likes the solution to implicitly resend the email when typing the same email again. Another part of me wants to have a "resend" button next to the invited email address. Both might be fine as well.
What do you think about the extra button?

(Just some thoughts, I'm happy to accept the current solution)

**Comment by mvellasco** [comment]
I think the button would be better for the users to understand what's going on. I've tried it before but I didn't succeed, I'll try again, and if I can't I'll ask for help on the slack channel.

**Comment by mvellasco** [comment]
Hello @tiltec, good evening!

I'm sorry but I couldn't make the button work, I'm still not familiarized enough with the stack :frowning_face: I'll continue to improve my skills, and I hope to be able to add this feature soon. Besides that, everything is working nicely by typing the email again.

Best Regards,
Miguel V.

**Pull request merged**
