### PR TITLE
Add pagination for pickups

### LINKED ISSUE #952: Add proper pickups pagination
Update: pagination might be the solution, see https://github.com/yunity/karrot-frontend/issues/952#issuecomment-434743691

---

Sometimes rendering the pickups page seems a bit slow. I used the new [vue performance tool](https://github.com/vue-perf-devtool/vue-perf-devtool) to record when loading that page:

pickups-performance

It shows it taking 745ms to render the `<Pickups>` component with the data I have in my localhost database, and the breakdown of which subcomponents make up that time.

I don't think it's a high priority issue, as maybe groups don't have that many pickups on the page, but something to be aware of, or to investigate if you feel particularly motivated :)

### PR DESCRIPTION
**Pull request by ang-zeyu**
Closes #952 

## What does this PR do?

Adds pagination for `GroupPickups.vue`

pagination

## Links to related issues
https://github.com/yunity/karrot-frontend/issues/952

## Checklist

- [x] added a test, or explain why one is not needed/possible...

I can't find an existing test for the `GroupPickups.vue` page, so I'm not sure if it was intentionally omitted. ( I'll be glad to add one if not though 😄 )

- [x] no unrelated changes
- [x] asked someone for a code review
- [x] joined #karrot-dev channel at https://slackin.yunity.org
- [x] added an entry to CHANGELOG.md (description, pull request link, username(s))

### CODE REVIEW

**Comment by tiltec** [comment]
Hi @ang-zeyu, welcome! Nice work :)

One thing I noticed is that the filter count becomes misleading: it shows "10/10", whereas it's rather 30 entries on 3 pages.

image

I wonder if we should move pagination into `PickupList`?

**Comment by ang-zeyu** [comment]
Hi @tiltec , thanks for looking through this!

> I wonder if we should move pagination into `PickupList`?

I realised less than 10 entries may show too actually, in addition to it being misleading, which isn't ideal.

Should we add an additional label of some sort beside the filter count to clarify what it shows, in addition to moving pagination into `PickupList`?

E.g. 
Perhaps something like `1-10 out of 23 results for <filter name>` ( from [amazon](https://www.amazon.com/b?node=18332383011&pf_rd_p=fed09b50-0584-490e-a698-ff8a751dc738&pf_rd_r=APSESKRX1ZSJ0AFAZWMT) )

Issue being internationalisation is needed, which's workflow I'm not too familiar with. ( is full internationalization usually pushed together with a feature here? )

**Comment by nicksellen** [comment]
> Issue being internationalisation is needed, which's workflow I'm not too familiar with. ( is full internationalization usually pushed together with a feature here? )

No, we use https://www.transifex.com/ for that so you don't need to worry about that - just make sure text is in English.

I actually wondered if this would be better and more consistent as an infinite scroll (as we use that pattern elsewhere).

I would also be happy with it as seperate pages though as it is here, just with the "1-10 out of 23 results" bit implemented.

**Comment by ang-zeyu** [comment]
Sorry for the late update!

> I actually wondered if this would be better and more consistent as an infinite scroll (as we use that pattern elsewhere).

Went with this, think its more consistent as well :+1:

**Pull request merged**
